version: '2.1'

services:
  app:
    build: ./app
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_started
    ports:
      - "6969:6969"
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5
    command: elasticsearch
    expose:
      - "9200"
      - "9300"
    volumes:
      - "/tmp/esdata:/usr/share/elasticsearch/data"
